apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-fee-calculator-user-interface.fullname" . }}
  labels:
    {{- include "laa-fee-calculator-user-interface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "laa-fee-calculator-user-interface.selectorLabels" . | nindent 4 }}
