development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  encoding: utf-8

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  encoding: utf-8

production:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  encoding: utf-8