development: &defaults
  secret_key_base: non-production-secret-key-base
test:
  <<: *defaults
production:
  <<: *defaults
  # Do not store this key in the repository, use kubernetes environment variable
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>