name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - setup_cloud

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t fee-calculator-ui .
