name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - setup_cloud

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t fee-calculator-ui .
      - name: Push to ECR
        id : ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: fee-calculator-ui
          image: ${{ secrets.ECR_NAME }}:${{ github.sha }}
