name: test-build-deploy-nonprod

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    needs: test
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit

  development:
    needs: build-and-push
    uses: ./.github/workflows/deploy-to-environment.yml
    secrets: inherit
    with:
      environment: Development
      values: values-dev.yaml

  staging:
    needs: build-and-push
    uses: ./.github/workflows/deploy-to-environment.yml
    secrets: inherit
    with:
      environment: Staging
      values: values-staging.yaml